name: 'Delete Preview Environment'
description: 'Delete a Full-Stack Preview Environment (on-demand, ephemeral) with Uffizzi Open Source (Compose + Uffizzi + Kubernetes)'
author: 'Adam Vollrath'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  id:
    description: 'Deployment ID string'
    required: true
  server:
    description: 'URL to Uffizzi'
    required: false
    default: 'https://app.uffizzi.com'
  username:
    description: 'Uffizzi username'
    required: false
  password:
    description: 'Uffizzi password'
    required: false
  project:
    description: 'Uffizzi project slug'
    required: false
  request-token:
    descrption: 'A token to access the pipeline information'
    required: false
  request-token-url:
    descrption: 'A url where the pipeline information can be accessed'
    required: false
  logger-key:
    description: 'Logger key'
    required: false

runs:
  using: 'docker'
  image: 'docker://uffizzi/cli:pr-201'
  args:
    - 'preview'
    - 'delete'
    - ${{ inputs.id }}
  env:
    UFFIZZI_PASSWORD: ${{ inputs.password }}
    UFFIZZI_SERVER: ${{ inputs.server }}
    UFFIZZI_USER: ${{ inputs.username }}
    UFFIZZI_PROJECT: ${{ inputs.project }}
    REQUEST_TOKEN: ${{ inputs.request-token }}
    REQUEST_TOKEN_URL: ${{ inputs.request-token-url }}
    CI_WORKFLOW: "true"
    LOGGER_KEY: ${{ inputs.logger-key }}
